export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTER";
export const GET_CHARACTER = "GET_CHARACTER";
export const UPDATE_CHARACTER_DETAIL = "UPDATE_CHARACTER_DETAIL";
export const ADD_CHARACTER_TO_FAVORITE = "ADD_CHARACTER_TO_FAVORITE";
export const REMOVE_CHARACTER_TO_FAVORITE = "REMOVE_CHARACTER_TO_FAVORITE";
export const SEARCH_CHARACTER = "SEARCH_CHARACTER";
export const SEARCH_CHARACTER_OK = "SEARCH_CHARACTER_OK"
export const UPDATE_SEARCH = "UPDATE_SEARCH";
