export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const TOTAL_PAGE = "TOTAL_PAGE";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";
export const UPDATE_BUTTON_PAGINATION = "UPDATE_BUTTON_PAGINATION";
