export const GENDER_FILTER = "GENDER_FILTER";
export const STATUS_FILTER = "STATUS_FILTER";
export const SPECIES_FILTER = "SPECIES_FILTER";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const SEARCH_CHARACTER = "SEARCH_CHARACTER";
export const SEARCH_CHARACTER_OK = "SEARCH_CHARACTER_OK"
export const UPDATE_SEARCH = "UPDATE_SEARCH";
